local M = {}

M.presets = {
  alpha = {
    "dashboard.nvim",
    "veil.nvim",
    "fsplash.nvim",
  },
  editor = {
    "treesj",
    "mini.comment",
    "mini.surround",
    "mini.align",
    "mini.extra",
    "nvim-recorder",
    "auto-indent.nvim",
    "dial.nvim",
  },
  organization = {
    "neorg",
    "orgmode",
    "eureka",
  },
  time = {
    "pomodoro.nvim",
    "due.nvim",
    "vim-wakatime",
    "usage-tracker.nvim",
    "pulse.nvim",
    "timewasted.nvim",
    "stand.nvim",
    "hydrate.nvim",
  },
  ai_passive = {
    "copilot.lua",
    "codeium.nvim",
    "tabnine-nvim",
    "huggingface/llm.nvim",
    "cmp-ai",
  },
  ai_activated = {
    "rgpt.nvim",
    "CodeGPT.nvim",
    "neural",
    "ChatGPT.nvim",
    "neoai.nvim",
    "naVi",
    "explain-it.nvim",
    "gsuuon/llm.nvim",
    "backseat.nvim",
    "wtf.nvim",
    "prompter.nvim",
    "aider.nvim",
    "juliusolson/gpt.nvim",
    "thmsmlr/gpt.nvim",
    "nvim-llama",
    "ollero.nvim",
    "gen.nvim",
  },
  lsp = {
    "nvim-lspconfig",
    "lsp-zero.nvim",
    "neoconf",
    "neodev",
    "mason.nvim",
    "mason-lspconfig.nvim",
    "none-ls.nvim",
  },
  lsp_tools = {
    "nvim-lspfuzzy",
    "lsp_lines.nvim",
    "aerial.nvim",
    "outline.nvim",
    "lsp-lens.nvim",
    "actions-preview.nvim",
    "output-panel.nvim",
    "lsp-toggle.nvim",
    "clear-action.nvim",
    "gentags.lua",
    "glance.nvim",
  },
  lsp_format = {
    "conform.nvim",
    "nvim-lint",
  },
  format_utils = {
    "pick-lsp-formatter.nvim",
    "nvim-rulebook",
  },
  build = {
    "executor.nvim",
    "compiler.nvim",
    "overseer.nvim",
    "runner.nvim",
    "rapid.nvim",
    "launch.nvim",
  },
  refactor = {
    "inc-rename.nvim",
    "ssr.nvim",
    "muren.nvim",
  },
  quickfix = {
    "nvim-bqf",
  },
  terminal = {
    "toggleterm.nvim",
  },
  fuzz = {
    "fzf-lua",
    "fzf",
    "fzf.vim",
  },
  telescope = {
    "telescope.nvim",
    "telescope-fzf-native",
  },
  telescope_extras = {
    "whaler.nvim",
    "telescope-tasks.nvim",
    "telescope-ports.nvim",
    "telescope-http.nvim",
    "telescope-find-pickers.nvim",
    "telescope-color-names.nvim",
    "telescope-cc.nvim",
    "telescope-undo.nvim",
    "telescope-media-files.nvim",
    "telescope-glyph.nvim",
    "telescope-symbols.nvim",
    "telescope-dap.nvim",
    "telescope-zoxide.nvim",
    "telescope-heading.nvim",
    "telescope-project.nvim",
    "telescope-menu.nvim",
    "telescope-lazy.nvim",
    "telescope-changes.nvim",
    "telescope-env.nvim",
    "telescope-repo.nvim",
    "telescope-file-browser.nvim",
    "telescope-env.nvim",
    "telescope-toggleterm.nvim",
  },
  ascii = {
    "comment-box.nvim",
    "nvim-comment-frame",
    "figban.nvim",
    "figlet.nvim",
    "venn.nvim",
  },
  icons = {
    "nerdy.nvim",
    "nerdicons.nvim",
    "icon-picker.nvim",
  },
  huevos = {
    "cellular-automaton.nvim",
    "zone.nvim",
    "duck.nvim",
  },
  juegos = {
    "tetris",
    "sudoku",
    "blackjack",
    "killersheep",
    "nvimesweeper",
    "shenzhen-solitaire",
    "speedtyper.nvim",
  },
  miscellaneous = {
    "code-shot.nvim",
  },
}

M.when_enabling = {}

return M
